name: CI
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - LICENSE
  push:
    paths-ignore:
      - '*.md'
      - LICENSE
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Test
        run: |
          sbt -v -Dfile.encoding=UTF-8 +check +test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                       -name "*.lock"               -delete || true